### ISSUE TITLE
keep poping this error 

### ISSUE THREAD

**Issue by rnrhds** [Kisspeace/NsfwBox#2]
Thread(19808) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of address 0000000000000070
Thread(30564) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of address 0000000000000020
 Thread(27168) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of address 0000000000000058
Thread(9640) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of address 0000000000000070
Thread(16220) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of address 0000000000000020
Thread(31284) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of address 0000000000000078
Thread(27924) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of address 0000000000000050
 Thread(24996) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of address 0000000000000030
Thread(6612) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of address 0000000000000070
Thread(10272) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of 
Thread(36332) DoOnException - {EXCEPTION!} - Access violation at address 000000000044CC65 in module 'NsfwBox.exe'. Read of address 0000000000000010

Cant open it both pc and andriod app, That error message keeps popping up in Windows, and only loading continues on mobile.
Is there any kind of pre-installation?

**Comment by Kisspeace** [comment]
Hello,
Whats your windows version and CPU architecture on PC? 
Whats your android version and CPU architecture on phone ?
"Is there any kind of pre-installation?" - No, on windows you just unarchive package that already include all necessary libraries and files. On android same, just normally APK installation.
Can you send me all files inside app folder on windows ?
And on android (if you has rooted device) file: /data/data/delphi.Kisspeace.NsfwBox/files/log.txt ?
Thank you.

**Comment by rnrhds** [comment]
window 10 22h2 19045.2251// android v 12 android not rooted, 
[log.txt](https://github.com/Kisspeace/NsfwBox/files/10228766/log.txt)

**Comment by Kisspeace** [comment]
Can you send me all files and directories that you have inside nsfwbox app folder ?

**Comment by rnrhds** [comment]
I reinstalled it after the error came out yesterday, so the log is little different from yesterday.
Either there is an EXCEPTION! error poped up or there is an icon in the window task bar, but nothing is loaded.
[LICENSE.md](https://github.com/Kisspeace/NsfwBox/files/10230306/LICENSE.md)
[log.txt](https://github.com/Kisspeace/NsfwBox/files/10230307/log.txt)
[you-did-well-debug-log.txt](https://github.com/Kisspeace/NsfwBox/files/10230308/you-did-well-debug-log.txt)

I compressed it, but they said couldn't upload some files on here, so I only uploaded able ones

**Comment by Kisspeace** [comment]
Thanks, now i have idea what i can do.

**Comment by Kisspeace** [comment]
Download this: [NsfwBox-x64-debug.zip](https://github.com/Kisspeace/NsfwBox/files/10240593/NsfwBox-x64-debug.zip)
1. Replace **NsfwBox.exe** in program directory with file from attached archive.
2. Delete **log.txt** and **you-did-well-debug-log.txt**
3. Delete **settings.json**  
4. Start **NsfwBox.exe**, then send me **log.txt** and **you-did-well-debug-log.txt** if it exists.
5. Do step **2**
6. Replace **settings.json** with file from attached archive
7. Do step **4**

**Comment by rnrhds** [comment]
[log.txt](https://github.com/Kisspeace/NsfwBox/files/10253476/log.txt)
[you-did-well-debug-log.txt](https://github.com/Kisspeace/NsfwBox/files/10253477/you-did-well-debug-log.txt)
1-4


[log.txt](https://github.com/Kisspeace/NsfwBox/files/10253480/log.txt)
7
error massage popup said 
' Exception EConvertError in module Nsfwbox.exe at 000000000003BF32.
'2022-12-13 10:11:02 is not a valid a valid date and time. '

And the time written on the pop-up is different from the time on my computer.

**Comment by Kisspeace** [comment]
I have installed your windows version on virtual machine(system language being English), and when i start program all works fine. Then i just change system language to Korean, and now have same EConvertError exception.

You can try this:
1. Change your system language to English.
2. Sign out and sign in again (Or just restart PC).
3. Reinstall program and try to run it.
4. Is it works ?

I try to fix it in next release (before new year) and make it work on different languages. Thanks.

**Comment by rnrhds** [comment]
It's working well just by changing the date display format to English. 
Thanks for your help!!

**Comment by Kisspeace** [comment]
🍕 You are welcome! And thank you for report.
