### ISSUE TITLE
How to use this Nsfwbox to download content from Rule34.xxx?

### ISSUE THREAD

**Issue by Gullinkambi07** [Kisspeace/NsfwBox#4]
I type tag in the search box and nothing happens

**Comment by Kisspeace** [comment]
You need to push search button again, or enter button on your keyboard.
![screenshot](https://user-images.githubusercontent.com/101427274/210173455-5f54e1cb-7677-452b-89d5-80a611b4665d.png)

**Comment by Gullinkambi07** [comment]
I see~ I should choose r34 app instead of r34 json api
Thank you for your help ^_^
